import numpy as np
import math
from core.models import *

def fast_pdf(x, mu, sigma):
    return (1 / (sigma * math.sqrt(2 * math.pi))) * math.exp(-0.5 * ((x - mu) / sigma)**2)

def from_LoA_to_thresholds(LoA: int) -> LevelOfAutomation:
    """
    Higher LoA -> Narrower uncertainty zone (Thresholds move toward 0.5).
    LoA 1: Widest zone (Human involved often).
    LoA 10: Narrowest zone (Machine takes all decisions).
    """
    if LoA == 1:
        return LevelOfAutomation(
            level=LoA,
            low_threshold=round(0, 4),
            high_threshold=round(1, 4)
        )
    elif LoA == 10:
        return LevelOfAutomation(
            level=LoA,
            low_threshold=round(0.5, 4),
            high_threshold=round(0.5, 4)
        )

    max_uncertainty_width = 1

    current_width = max_uncertainty_width * (1 - (LoA - 1) / 9)

    low_threshold = 0.5 - (current_width / 2)
    high_threshold = 0.5 + (current_width / 2)

    return LevelOfAutomation(
        level=LoA,
        low_threshold=round(low_threshold, 4),
        high_threshold=round(high_threshold, 4)
    )

def get_posterior(x: float, mu_s:float, mu_n: float, sigma: float, prior: float):
    # Calculate likelihoods (PDF values)
    likelihood_s = fast_pdf(x, mu_s, sigma)
    likelihood_n = fast_pdf(x, mu_n, sigma)

    # Bayes' Theorem
    posterior_s = (likelihood_s * prior) / (likelihood_s * prior + likelihood_n * (1 - prior))
    return posterior_s

def compute_combined_posterior(x: float, mu_s:float, mu_n: float, sigma: float, p_auto: float):
    """
    x_human: The raw observation value from the human
    d_human: The human's sensitivity (determines the means)
    p_auto: The posterior probability generated by the automation (acting as the new prior)
    """
    # Calculate Human Likelihoods
    likelihood_s = fast_pdf(x, mu_s, sigma)
    likelihood_n = fast_pdf(x, mu_n, sigma)

    # BAYESIAN UPDATE:
    # Use p_auto as the prior for this stage
    fused_posterior = (likelihood_s * p_auto) / \
                      (likelihood_s * p_auto + likelihood_n * (1 - p_auto))

    return fused_posterior

def run_simulation(
        number_of_iterations: int,
        level_of_automation_stage_2: int,
        level_of_automation_stage_3: int,
        prior: float,
        sys_d: float,
        h_d: float,
        automation_threshold: float = 0.5,
        human_threshold: float = 0.4
) -> OutcomeVariables:

    wl = 0
    acc = 0
    LoA_2 = from_LoA_to_thresholds(level_of_automation_stage_2)
    LoA_3 = from_LoA_to_thresholds(level_of_automation_stage_3)
    for i in range(number_of_iterations):
        # stage 2 - Information Analysis
        signal_or_noise = np.random.uniform(0, 1)
        if signal_or_noise > prior:
            signal_or_noise = 'N'
            system_info = np.random.normal(0 - sys_d/2, 1)
            human_info = np.random.normal(0 - h_d / 2, 1)
        else:
            signal_or_noise = 'S'
            system_info = np.random.normal(sys_d/2, 1)
            human_info = np.random.normal(h_d / 2, 1)
        system_posterior = get_posterior(system_info, sys_d / 2, -sys_d / 2, 1, prior)

        if LoA_2.level >= 10:
            uncertain_2 = False
        else:
            uncertain_2 = (LoA_2.low_threshold <= system_posterior <= LoA_2.high_threshold)

        if uncertain_2:
            wl += 1
            # Human fuser improves the data
            fused_posterior = compute_combined_posterior(human_info, h_d / 2, -h_d / 2, 1, system_posterior)
        else:
            # AI handles analysis alone
            fused_posterior = system_posterior
        if LoA_3.level >= 10:
            uncertain_3 = False
        else:
            uncertain_3 = (LoA_3.low_threshold <= fused_posterior <= LoA_3.high_threshold)

        if uncertain_3:
            wl += 1
            # Human makes the final decision
            state = 'S' if fused_posterior > human_threshold else 'N'
        else:
            # AI makes the final decision
            state = 'S' if fused_posterior > automation_threshold else 'N'

        if state == signal_or_noise:
            acc += 1

    return OutcomeVariables(workload=round(wl / (number_of_iterations*2), 2),
                            accuracy=round(acc / (number_of_iterations), 2))
