from scipy.stats import norm
import numpy as np
import math
from core.models import *

def fast_pdf(x, mu, sigma):
    return (1 / (sigma * math.sqrt(2 * math.pi))) * math.exp(-0.5 * ((x - mu) / sigma)**2)

def from_LoA_to_thresholds(LoA: int) -> LevelOfAutomation:
    """
    Higher LoA -> Narrower uncertainty zone (Thresholds move toward 0.5).
    LoA 1: Widest zone (Human involved often).
    LoA 10: Narrowest zone (Machine takes most decisions).
    """
    if LoA == 10:
        return LevelOfAutomation(
            level=LoA,
            low_threshold=round(1.1, 4),
            high_threshold=round(-0.1, 4)
        )

    max_uncertainty_width = 1

    current_width = max_uncertainty_width * (1 - (LoA - 1) / 9)

    low_threshold = 0.5 - (current_width / 2)
    high_threshold = 0.5 + (current_width / 2)

    return LevelOfAutomation(
        level=LoA,
        low_threshold=round(low_threshold, 4),
        high_threshold=round(high_threshold, 4)
    )
    return LevelOfAutomation(level=LoA, low_threshold=low_threshold, high_threshold=high_threshold)

def get_posterior(x: float, mu_s:float, mu_n: float, sigma: float, prior: float):
    # Calculate likelihoods (PDF values)
    likelihood_s = fast_pdf(x, mu_s, sigma)
    likelihood_n = fast_pdf(x, mu_n, sigma)

    # Bayes' Theorem
    posterior_s = (likelihood_s * prior) / (likelihood_s * prior + likelihood_n * (1 - prior))
    return posterior_s

def compute_combined_posterior(x: float, mu_s:float, mu_n: float, sigma: float, p_auto: float):
    """
    x_human: The raw observation value from the human
    d_human: The human's sensitivity (determines the means)
    p_auto: The posterior probability generated by the automation (acting as the new prior)
    """
    # Calculate Human Likelihoods
    likelihood_s = fast_pdf(x, mu_s, sigma)
    likelihood_n = fast_pdf(x, mu_n, sigma)

    # BAYESIAN UPDATE:
    # Use p_auto as the prior for this stage
    fused_posterior = (likelihood_s * p_auto) / \
                      (likelihood_s * p_auto + likelihood_n * (1 - p_auto))

    return fused_posterior

def run_simulation(
        number_of_iterations: int,
        level_of_automation: int,
        prior: float,
        sys_d: float,
        h_d: float
) -> OutcomeVariables:

    wl = 0
    acc = 0
    LoA = from_LoA_to_thresholds(level_of_automation)
    for i in range(number_of_iterations):
        signal_or_noise = np.random.uniform(0, 1)
        if signal_or_noise < prior:
            signal_or_noise = 'N'
            system_info = np.random.normal(0 - sys_d/2, 1)
            human_info = np.random.normal(0 - h_d / 2, 1)
        else:
            signal_or_noise = 'S'
            system_info = np.random.normal(sys_d/2, 1)
            human_info = np.random.normal(h_d / 2, 1)
        system_posterior = get_posterior(system_info, sys_d / 2, -sys_d / 2, 1, prior)
        if system_posterior < LoA.low_threshold or system_posterior > LoA.high_threshold:
            state = 'S' if system_posterior > 0.5 else 'N'
        else:
            # Uncertainty Zone: Human-Augmented Analysis
            wl += 1
            fused_posterior = compute_combined_posterior(human_info, h_d / 2, -h_d / 2, 1, system_posterior)
            state = 'S' if fused_posterior > 0.5 else 'N'

        if state == signal_or_noise:
            acc += 1

    return OutcomeVariables(workload=round(wl / number_of_iterations, 2),
                            accuracy=round(acc / number_of_iterations, 2))
